version: '3.9'

networks: 
  rubi:
    driver: bridge
    
services:
    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3.9-management
        environment:
          RABBITMQ_CONFIG_FILE: ./rabbitmq.conf
        ports:
          - "5673:5673"
          - "15672:15672"
        volumes:
          - .:/app
        working_dir: /app
        networks:
          - rubi